### ISSUE TITLE
Agent Log Path not connecting

### ISSUE THREAD

**Issue by mitch053** [rzander/sccmclictr#143] opened 2019-11-21 23:20 UTC
I am running 1.0.5.5. Seems that when I try to connect to the Agent Log Path, or CCMSetup Path, or Cache Path, I does not connect to the folder on the remote client.  Instead brings up my local documents folder.  This has always worked in the past, I think it stopped with 1.0.5.5.  I use an account under connection options which has admin rights on all clients and I have no problem connecting to the client.  Just when trying to get to the logs it seems like it may be using my logged on credentials instead of the account in connection options.  I can get to the logs fine using the old 2.0.4.2 version of client center.  Everything else in the 1.0.5.5 version seems to be working fine.  I can connect, force client actions, etc.  Just can't bring up the remote client logs.

**Comment by rzander** [comment] 2019-11-22 07:16
Just tested it with V1,0,5,5 and it's working here...
If you click on the magnifying glass button, do you get the path like:
![image](https://user-images.githubusercontent.com/11909453/69405265-81143380-0cff-11ea-8298-b3d319604261.png)
The Path does come from a Reg-Key on the remote client: 
```PowerShell
 (Get-ItemProperty("HKLM:\SOFTWARE\Microsoft\SMS\Client\Configuration\Client Properties")).$("Local SMS Path")
```

Does this Key exists ? Does your User have the rights to access C$ or Admin$ on the remote client ?

**Comment by mitch053** [comment] 2019-11-22 15:34
The magnifying glass does come back with the correct value
"C:\Windows\CCM\Logs". Running the Get-ItemProperty command  on the remote
client returns C:\Windows\CCM\
In fact I can use client center to connect to the remote client and use the
open console command to remote powershell in. I can connect to C$ and
admin$.  If I use use the old version of client center (2.0.4.2) to connect
to the same client with the same credentials I can open the logs.  Once I
have done this, if I go back to the current client center and connect to
the same client, I can now get to the logs because I have already
established a connection using the old client center tool.

**Comment by rzander** [comment] 2019-11-22 16:00
Need some more Information to reproduce:
- are you using stored credentials ?
- are you running ClientCenter as another user ?
- are you using the MSIX/Store Version ?

**Comment by mitch053** [comment] 2019-11-22 16:22
I store the admin credentials in the tool. The acount has full admin rights
to every workstation client.  I launch the tool with my normal user account
which does not have any admin rights to the clients.  I am using the MSI
version downloaded from github
(Client.Center.for.Configuration.Manager_v1.0.5.5.msi).
[image: image.png]

connected to client successfully.  I can perform all operations in tool
except opening logs but the search icon shows the correct path.

[image: image.png]

Clicking the icon to open the log folder takes much longer than usual and
eventually brings up my local documents folder.

[image: image.png]

**Comment by theaquamarine** [comment] 2019-11-22 16:45
Possibly the issue is CustomTools_Explorer.xaml.cs Appears to not have the ConnectIPC bit from Explorer.xaml.cs?
https://github.com/rzander/sccmclictr/blob/26b7688382c5db18683b23eff9e0229fa487ad06/Plugins/Plugin_Explorer/Explorer.xaml.cs#L88

**Comment by rzander** [comment] 2019-11-22 17:05
Correct, but it will not be able to connect because username and password where missing... 
connectIPC requires Username and password in plain text :-(
```C#
        internal int connectIPC(string Hostname, string UserName, string Password)
        {
            NETRESOURCE ConnInf = new NETRESOURCE();
            ConnInf.dwType = RESOURCETYPE_ANY;
            ConnInf.RemoteName = @"\\" + Hostname;
            IntPtr hWnd = IntPtr.Zero;
            return WNetAddConnection3(hWnd, ref ConnInf, Password, UserName, 0);
        }
```

**Comment by rzander** [comment] 2019-12-26 17:53
Fixed with https://github.com/rzander/sccmclictr/commit/c7dd3a4e257f3b707df8b2a439b7f6fc7a9bd0ee

**Closed** 2019-12-26 17:53 UTC

**Comment by mitch053** [comment] 2020-01-17 18:47
Hi.  Will this fix be incorporated into a new release?  the latest release available 1.0.5.5 does not have this fix.

**Comment by mitch053** [comment] 2020-02-06 20:44
Hi, I just tried V1.0.6.1 but Fix#143 is still behaving the same way as before.  I launch the tool with my standard user account which does not have rights to the SCCM clients.  I populate the connection options with an account and password that does have administrative rights on clients.  I can connect to the clients and do anything in the tool. I can even look a a log using the log monitoring feature.  When I click the magnifying glass next to agent log path it returns the correct value "C:\Windows\CCM\Logs". But when attempting to connect it hangs for a while then shows me my own documents folder.  If I try launching the tool with run as different user and use an account that has admin rights on the clients, all functions in the tool still work correctly.  But if I try to connect to the agent log path, in this instance it will prompt me for credentials.  I can successfully connect to the agent log path using the old 2.4 version of the tool.

**Comment by rzander** [comment] 2020-02-12 16:59
I agree, there was an Issue with the preview...  Just published an updated Version. Let me know if it's working...

**Comment by mitch053** [comment] 2020-02-13 21:31
Yes, that did work.  Thank you.
